# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blasbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
